version: '3'

services:
  videojuegos:
    build: videojuegos5
    mem_limit: 2048m
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:mysql://videojuegosapp:3306/videojuegos?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USER: root
      DB_PASSWORD: 2003
      DB_DIALECT: org.hibernate.dialect.MySQL8Dialect
    restart: always
    depends_on:
      videojuegosapp:
          condition: service_healthy
  videojuegosapp:
    image: mysql:8.0.33 
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 2003
      MYSQL_PASSWORD: 2003
      MYSQL_DATABASE: videojuegos
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10